jabardigitalservice/pikobar-rapidtest-api

app/Http/Controllers/Rdt/RdtEventController.php, tests/Feature/RdtEvents/ShowAllRdtEvent.php
mas pagination udah sya tambah, paginate nya mengunakan query string  url?perPage=jumlahPerPage dan default 15 page 
dan bisa di akses tanpa query string
=> add pagination in show all RDT event

app/Entities/RdtApplicant.php, app/Enums/PersonCaseStatusEnum.php, app/Http/Controllers/Rdt/RdtRegisterController.php, app/Http/Requests/Rdt/RdtRegisterRequest.php, database/migrations/2020_06_29_073723_add_column_peope_status_to_table_rdt_applicants.php
Untuk nilai di colum people_status :
- odp
- pdp
- otg
- tidak_ketiganya
- tidak_tahu
=> Update api rdt registrasi status orang

app/Http/Controllers/Rdt/RdtEventParticipantImportController.php, app/Http/Requests/Rdt/RdtInvitationImportRequest.php
=> Add phone number and notification to invitaion

app/Http/Controllers/Rdt/RdtEventParticipantAddController.php
update status event menjadi draft ke published ketika menambahkan peserta ke event
=> update status event to published if draft

app/Http/Controllers/Rdt/RdtEventParticipantAddController.php
=> fix comparison enum status

app/Http/Requests/Rdt/RdtRegisterRequest.php
Validasi NIK agar hanya bisa digunakan sekali ketika melakukan register.
CC : @yohang88 
https://trello.com/c/Vsa6gdKC/90-nik-hanya-bisa-digunakan-sekali-ketika-registrasi
=> validasi nik agar hanya bisa digunakan sekali

app/Http/Controllers/Rdt/RdtEventParticipantImportController.php
refactoring controller import participant
=> Housekeeping

app/Http/Controllers/Checkin/RdtEventParticipantsController.php
Perbaikan sorting nama perserta yang muncul berdasarkan nama.
CC : @yohang88
=> Perbaikan sorting nama peserta

app/Http/Controllers/Checkin/RdtEventParticipantsController.php
Perbaikan column attended_at yang value nya selalu null.
CC : @yohang88
=> Fix Bug attended_at return null

app/Http/Controllers/Rdt/RdtEventParticipantListExportF1Controller.php
Cors Handler Export Participants Format F1
cc : @yohang88
=> Cors Handler Export Participants Format F1

app/Http/Controllers/Rdt/RdtApplicantController.php, app/Http/Controllers/Rdt/RdtEventController.php
penyesuaian jumlah data per page sesuai dengan request dari frontend ( 50,100, dan 500 )
CC : @yohang88
=> perbaikan jumlah data pagination

app/Entities/RdtApplicant.php, app/Http/Requests/Rdt/RdtRegisterRequest.php, database/migrations/2020_09_17_090249_add_column_birth_place.php, tests/Feature/RdtRegisterTest.php
Menambahkan Field birth_place untuk menyimpan informasi tempat lahir.
CC : @yohang88
=> Add colum Tempat Lahir

app/Http/Controllers/Rdt/RdtEventParticipantDetailController.php, routes/api.php
menampilkan detail dari peserta event.
https://trello.com/c/pfSPa5Lo/96-admin-bisa-melihat-identitas-yang-terdaftar-di-kegiatan
https://trello.com/c/jCY7KuPh/99-kegiatan-bug-ubah-kode-sampel
cc : @yohang88
=> Detail participant from event

app/Http/Controllers/Rdt/RdtEventParticipantListController.php
Penyesuaian jumlah request data perhalaman pada halaman daftar peserta event.
cc : @yohang88
=> event participants list paging adaptability

app/Http/Resources/RdtApplicantResource.php
add birth_place parameter response
=> add birth_place parameter response

app/Entities/RdtEvent.php, app/Http/Resources/RdtEventResource.php, database/migrations/2020_09_25_060612_add_host_type_to_rdt_event.php
penambahan colum host_type ke tabel rdt_event yang nanti akan digunakan ketika export peserta test format F1.
https://trello.com/c/aRw89I9i/106-tambah-edit-kegiatan-admin-bisa-memasukan-kategori-penyelenggara-dan-memasukan-data-penyelenggara-dari-master-data-labkes
CC : @yohang88
=> Add host type to event

app/Http/Controllers/Rdt/RdtApplicantController.php, app/Http/Controllers/Rdt/RdtEventParticipantListExportF1Controller.php
Filter data invitation yang tetap muncul meskipun data event nya dihapus.
perbaikan format tanggal menjadi d-m-Y pada export data dengan format F1.
Related Task :
https://trello.com/c/EDmsLsIQ/100-riwayat-hasil-test
https://trello.com/c/i4taU4Ak/87-kegiatan-revisi-export
cc : @yohang88
=> show invitationt history if event exist

app/Entities/RdtApplicant.php, app/Http/Resources/RdtApplicantResource.php
Penambahan relasi data ke model occupation_type untuk mendapatkan nama pekerjaan nya.
cc :  @yohang88
=> Add relation to occupation type

app/Http/Controllers/Rdt/RdtEventParticipantListExportF1Controller.php
muncul error jika keriteria peserta tidak sesuai dengan yang sudah di definisikan ( ODP, PDP, dan lain lain.
https://sentry.digitalservice.id/organizations/jabardigitalservice/issues/1405/?project=11&query=is%3Aunresolved
cc : @yohang88
=> Fix error undefined index person status

app/Http/Controllers/Rdt/RdtEventParticipantAddController.php
Perbaikan bisniss proses yang semula status kegiatan menjadi publish ketika admin menambahkan peserta kesebuah event, ekspektasinya status kegiatan tetap draft.
https://trello.com/c/c6NS0Rl9/107-kegiatan-bug-status-kegiatan-published-draft
CC : @yohang88
=> Status Kegiatan Menjadi Auto Publish Setelah Menambahkan Peserta

app/Http/Controllers/Rdt/RdtEventParticipantAddController.php, app/Http/Controllers/Rdt/RdtEventParticipantListExportF1Controller.php, config/cors.php, database/factories/RdtApplicantFactory.php
Export Laporan Peserta  Event Format F1
Perbaikan Bug Status Event Otomatis Publish Ketika Menambahkan Peserta
CC @yohang88
=> PR 10 Oktober 2020

app/Http/Controllers/Rdt/RdtEventParticipantListExportF1Controller.php
Filter data yang ditampilkan hanya peserta yang memiliki kode sampel.
https://trello.com/c/2opHZFeK/122-ekspor-f1-hanya-menampilkan-peserta-yang-memiliki-kode-sample-saja
cc : @yohang88
=> add filter kode sample not null

packages/robsontenorio/laravel-keycloak-guard/src/KeycloakGuard.php
Filter Export F1 hanya yang mempunyai kode sampel.
fix issue backend JDS2
cc : @yohang88
=> Marge Filter F1 Dan Fix Issue  backend JDS 

app/Http/Controllers/Rdt/RdtInvitationLabResultUpdateController.php, app/Http/Requests/Rdt/RdtInvitationLabResultUpdateRequest.php, routes/api.php
Ednpoint yang akan digunakan untuk melakukan perubahan hasil pemeriksaan.
https://trello.com/c/DBpbqTrs/125-admin-bisa-mengubah-hasil-tes-peserta-dari-dalam-dashboard
cc : @yohang88
=> Update lab result type

app/Http/Resources/RdtApplicantResource.php
Penambahakan informasi apakah profile applicant sudah lengkap atau belum ketika user melakuakn check.
cc : @yohang88
=> check if profile complate

app/Http/Controllers/Rdt/RdtEventParticipantListExportF1Controller.php
Penambahan Kategori kegiatan ketika export F1, format kategorinya nama event tanggal
https://trello.com/c/pwRLGogz/132-export-f1-data-di-kategori-diganti-dengan-judul-kegiatan-ddmmyyyy
CC : @yohang88
=> add category kegiatan

app/Http/Controllers/Rdt/RdtEventParticipantListController.php
Penambahan filter pencarian peserta event berdasarkan tempat bekerja.
https://trello.com/c/qLON7nit/139-admin-bisa-mengsearch-user-berdasarkan-nama-tempat-kerja-mereka
cc : @yohang88
=> filter pencarian berdasarkan tempat kerja

app/Http/Controllers/Rdt/RdtEventParticipantListExportF1Controller.php
Penambahan host_type dan ubah tanggal lahir menjadi Y-m-d ketika export F1.
https://trello.com/c/B2QvKmcO/142-pergantian-tanggal-lahir-di-f1
https://trello.com/c/flzctqmR/140-tidak-ada-data-instansi-pengirim-di-ekspor-f1
cc : @yohang88
=> Penambahan host name ketika export f1

app/Http/Controllers/Rdt/RdtEventParticipantListController.php
penambahan fitur pencarian peserta event yang akan di invite berdasarkan NIK.
https://trello.com/c/r5dU4Dy7/146-admin-bisa-search-by-nik-ketika-tambah-peserta
cc : @yohang88
=> penambahan query pencarian bedasarkan NIK

app/Http/Controllers/Rdt/RdtEventParticipantListExportF1Controller.php
penambahan joint dengan tabel fasyankes untuk mendapatkan value fasyankes_id ketika export excel format F1.
cc : @yohang88
=> Penambahan fasyankes_id ketika export format F1

app/Http/Resources/RdtApplicantResource.php
penambahan data riwayat kunjungan dan penyakit bawaan pada response detail peserta
https://trello.com/c/SAbCMQqn/144-improvement-detail-daftar-peserta
cc : @yohang88
=> penambahan data riwayat kunjungan dan penyakit bawaan

app/Http/Controllers/Rdt/RdtEventParticipantListController.php
Perbaikan pencarian peserta  yang akan di invite ke evetn berdasarkan NIK.
cc : @yohang88
=> perbaikan pencarian berdasarkan nik

app/Http/Controllers/Rdt/RdtEventParticipantListExportF1Controller.php
Penyesuaian value dari field person_status, di sesuaikan dengan format yang dipakai oleh labkes.
cc : @yohang88
=> penyesuaikan person status dengan format dari labkes

app/Http/Controllers/Rdt/RdtApplicantController.php
penambahan support pencarian berdasarkan NIK ketika akan melakukan undangan perserta kedalam sebuah event.
https://trello.com/c/r5dU4Dy7/146-admin-bisa-search-by-nik-ketika-tambah-peserta
cc : @yohang88
=> penambahan pencarian berdasarkan nik

app/Http/Controllers/Rdt/RdtEventParticipantListController.php
refactor agar function __invoke tidak lebih dari 25 line code.
cc : @yohang88
=> Refactor rdt event list participant

app/Http/Controllers/Rdt/RdtCheckinBulkController.php, routes/api.php
Bulk checkin adalah proses dimana aplikasi mobile bisa melakukan sinkronisasi data checkin secara simultan.
Related Task :
https://trello.com/c/SWsia5yW/129-petugas-bisa-mengecek-data-peserta-meskipun-tidak-ada-koneksi-internet
cc : @yohang88
=> Bulk checkin

app/Http/Controllers/Rdt/RdtApplicantController.php
Penambahan filter kriteria dan periode pendaftaran pada data peserta.
https://trello.com/c/7mWhUxDV/158-calon-peserta-dan-daftar-peserta-tambahan-filter-di-dalam-calon-peserta-dan-daftar-peserta
=> add filter person status and registration periode

app/Http/Controllers/Rdt/RdtApplicantController.php
perubahan filter kriteria yang tadinya bisa multiple menjadi single dari frontend.
CC : @yohang88
=> perbaikan filter kriteria data peserta

app/Entities/RdtInvitation.php, app/Http/Controllers/Rdt/RdtEventNotifyParticipantController.php, app/Http/Controllers/Rdt/RdtEventNotifyTestResultController.php, database/migrations/2020_11_30_033715_add_sender_notif_to_table_invitation.php
Menambahkan pencatatan user yang melakukan blast notifikasi.
cc : @yohang88
=> Add sender wa blast invitation

app/Http/Controllers/Rdt/RdtApplicantController.php
Perbaikan bug filter range pendaftaran peserta yang kadang tidak muncul.
Related Task:
https://trello.com/c/7mWhUxDV/158-calon-peserta-dan-daftar-peserta-tambahan-filter-di-dalam-calon-peserta-dan-daftar-peserta
CC : @yohang88
=> perbaikan bug filter peserta berdasarkan tanggal pendaftaran

app/Http/Controllers/Rdt/RdtCheckinBulkController.php
Penambahan filter event code ketika melakukan checkin, karna ternyata 1 registration code bisa dipakai di beberapa kali event, sebelumnya hanya filter berdasarkan registration code saja.
cc : @yohang88
=> add filter registration code and event code on checkin

app/Entities/RdtEvent.php, app/Http/Controllers/Rdt/RdtEventController.php, app/Observers/RdtEventObserver.php, database/migrations/2020_12_01_061541_add_created_by_updated_by_at_event.php
penambahan informasi user yang melakukan pembuatan dan update data event.
https://trello.com/c/SauAXso6/170-penambahan-keterangan-user-di-log
CC : @yohang88
=> Add user log activity

app/Http/Controllers/Rdt/RdtRegisterController.php
flow bisniss sekarang memungkinkan calon peserta untuk melakukan pendaftaran dari link pendaftaran pada halaman event ( dengan membawa session id) dan pendaftran dari pikobar dengan tidak membawa session id.
jika calon peserta melakukan pendaftaran dengan membawa session id maka  pada response hasil pendaftaran akan muncul informasi event nya, jika tidak maka informasi event nya akan menjadi null ( request dari FE ).
cc : @yohang88
=> add null if event not exist

app/Http/Controllers/Rdt/RdtCheckinBulkController.php, app/Http/Requests/Checkin/RdtCheckinBulkRequest.php
Penambahan Validasi Inputan Bulk Checkin.
CC : @yohang88
=> Validation bulk checkin

app/Http/Controllers/Rdt/RdtEventParticipantListController.php
penambahan support pencarian peserta yang ingin di invite berdasarkan session id.
cc : @yohang88
=> add support search by session id

app/Http/Controllers/Rdt/RdtApplicantController.php
penambahan suppoer pencarian berdasarkan session id pada list peserta / calon peserta.
cc: @yohang88
=> pernambahan support search by session id

app/Http/Controllers/SyncToLabkesController.php
perbaikan endpoint untuk sinkronisasi ke labkes labkes.
kondisi sekarang semua response code nya jadi 200.
sekalia perbaikan endpoint labkes yang ternyata sudah berubah
=> perbaikan endpoint dan response code

app/Http/Controllers/Rdt/RdtRegisterController.php
penambahan informasi waktu kloter melakukan test
cc : @yohang88
=> add event schedule

app/Http/Controllers/Rdt/RdtEventParticipantListExportF1Controller.php, app/Http/Controllers/SyncToLabkesController.php
Perubahan category dari semula nama event menjadi tempat kerja.
cc : @yohang88
=> change category to workplace_name

app/Http/Controllers/Rdt/RdtEventParticipantListExportF1Controller.php, app/Http/Controllers/SyncToLabkesController.php
perubahan kategori degan format nama event tanggal checkin(ddmmYY).
contoh : test massif sukabumi 01122020
https://trello.com/c/z6cBv5Sq/195-kategori-di-f1-dikembalikan-menjadi-nama-event-dan-tanggal
cc : @yohang88
=> change category name to eventname ddmmyyyy

app/Http/Controllers/Master/FasyankesListController.php
penambahan support filter berdasarkan type fasyankes.
https://trello.com/c/LfzH5QX4/193-nama-yang-muncul-di-penyelenggara-disamakan-dengan-jenis-penyelenggara
cc : @yohang88
=> add filter by fasyankes type

app/Http/Controllers/SyncToLabkesController.php
penambahan parameter fasyankes_id untuk dikirim ke labkes.
CC : @yohang88
=> penambahan fasyankes_id untuk dikirim ke labkes

app/Http/Controllers/Rdt/RdtRegisterController.php, app/Http/Requests/Rdt/RdtRegisterRequest.php
perubahan bisniss proses menjadi peserta bisa daftar lebih dari sekali dengan NIK yang sama, tapi di data peserta cuman satu saja data yang tersimpan dengan data kunci nya NIK.
https://trello.com/c/FQgHaFTm/198-user-bisa-mendaftar-dengan-nik-yg-sama-tapi-terdaftar-dalam-1-akun
CC : @yohang88
=> Peserta bisa daftar lebih dari satu kali

README.md, app/Http/Controllers/Rdt/RdtApplicantController.php, config/app.php, config/url-signer.php
Overview :
- Menambahkan README untuk memudahkan setup environment development
- Fixing bug tambah peserta 2x pada kegiatan yang sama
Note:
- Tested on postman sesuai dengan expected result pada task trello
cc mas @yohang88
=> Fixing bug development tambah peserta

app/Http/Controllers/SyncToLabkesController.php, resources/lang/id/response.php, routes/api.php
Overview :
- Penyesuaian payload ketika POST data ke Simlab
- Merapihkan code menggunakan phpcs dan phpfmt (extension vscode)
- Sudah concalling dgn programmer simlab (ayocoding) terkait keselarasan data
Note:
- Tested on postman data berhasil terkirim ke simlab
=> Fixing bug sync to labkes

app/Http/Controllers/Rdt/RdtApplicantController.php
Overview : 
- Merubah sorting from created_at to updated_at on applicant list
Note:
- Tested
=> change sorting from created at to updated at

app/Http/Controllers/Rdt/RdtApplicantController.php
Overview:
- Tertinggal untuk filter cast by registration_date_start dan registration_date_end masih merefer ke created_at, harusnya saat ini merefer ke updated_at :smile: 
cc: mas @yohang88 :man_dancing:
=> Change sorting daftar peserta

.gitignore, Dockerfile, Jenkinsfile, README.md, app/Entities/RdtApplicant.php, app/Enums/SymptomsInteraction.php, app/Http/Controllers/Rdt/RdtApplicantController.php, app/Http/Controllers/Rdt/RdtEventParticipantImportController.php, app/Http/Controllers/Rdt/RdtEventParticipantListController.php, app/Http/Controllers/Rdt/RdtEventParticipantSetLabCodeController.php, app/Http/Controllers/Rdt/RdtRegisterController.php, app/Http/Controllers/SyncToLabkesController.php, app/Notifications/CheckinThankYou.php, app/Observers/RdtEventObserver.php, config/app.php, config/url-signer.php, database/factories/RdtApplicantFactory.php, phpcs.xml, resources/lang/id/response.php, routes/api.php
Overview:
- Point 1, 2, 3 sudah include pada branch develop
Note:
- Tested by QA
cc mas @yohang88 :dancers:
=> Ready to up production

app/Http/Controllers/Rdt/RdtEventParticipantSetLabCodeController.php
--Expected result--
--Actual result (kode sample bisa sama alias duplikat) --
Overview:
- Menambahkan sedikit logic untuk memvalidasi kode sample jika sudah pernah digunakan atau sama
- Menggunakan HTTP_Response sebagai return code http agar mudah dimengerti oleh programmer lain (biasanya hanya melemparkan nomor http kodenya (400 untuk bad request))
Note:
- Tested
cc mas @yohang88 @sandisunandar99
=> add validation when kode sample already exists or used

app/Http/Requests/Rdt/RdtRegisterRequest.php
Overview:
- Penyesuaian validasi di backend terkait input microsite
Task Trello -> This PR refer on -> https://trello.com/c/Ynm3GBXU
cc mas @yohang88
=> adjustment validation on microsite

app/Http/Controllers/SyncToLabkesController.php
current result error
expected result error
Overview:
- Menampilkan message error ketika integrasi simlab (sebelumnya hanya null sehingga user kebingungan) :grin: 
Note:
- Tested
=> Fixing message error integrasi simlab

.github/workflows/main.yml, app/Http/Controllers/Rdt/RdtApplicantController.php, app/Http/Controllers/Rdt/RdtEventParticipantListController.php, app/Http/Controllers/Rdt/RdtEventParticipantSetLabCodeController.php, app/Http/Controllers/SyncToLabkesController.php, app/Http/Requests/Rdt/RdtRegisterRequest.php, app/Http/Resources/RdtInvitationResource.php, database/migrations/2021_02_16_043716_add_field_status_on_simlab_on_table_rdt_invitations.php, tests/Feature/RdtRegisterTest.php
Ready to up production
Note:
- Perlu dilakukan php artisan migrate setelah PR ini merged di prod
( karna ada migrasi field baru )
=> PR Up To Production

app/Listeners/Rdt/InviteToEventByCode.php
This PR refer to task --> https://trello.com/c/DVWFzJNB
Overview:
- Memperbaiki bug data applicant bisa lebih dari satu (nik + registration code) sama pada satu kegiatan (registration via microsite berkali2)
Note:
- Tested on case 1 (jika nik sudah digunakan dikegiatan yang sama, maka akan meng-overwrite data tersebut, tidak menjadi double)
- Tested on case 2 (kondisi existing jika data applicant baru maka membuat record baru pada kegiatan tersebut)
=> fixing bug data applicant double in same event

resources/lang/id/response.php
Adjusment response message [Requested from FE]
Overview:
- Change some wording message response 
=> adjustment response message request from FE

app/Http/Controllers/SyncToLabkesController.php
Overview:
- Penyesuaian response perubahan simlab
- Refactor duplicate function
Note:
- Tested on concall with QA & FE
=> penyesuaian response perubahan simlab

app/Http/Controllers/Rdt/RdtApplicantController.php, app/Http/Controllers/Rdt/RdtEventParticipantAddController.php, app/Listeners/Rdt/InviteToEventByCode.php
Refer to task --> https://trello.com/c/uBmG04Da
Overview:
- Peserta bisa daftar lewat link registrasi kegiatan lebih dari satu kali
- Petugas dapat menambahkan peserta lebih dari satu kali lewat backoffice
Note:
- Tested
cc: mas @yohang88 :smile:
=> update applicants can doube in same event

app/Entities/RdtEvent.php, app/Enums/JenisRegistrasi.php, app/Http/Controllers/Rdt/RdtEventController.php, app/Http/Controllers/SyncToLabkesController.php, app/Http/Requests/Rdt/RdtEventStoreRequest.php, database/factories/RdtEventFactory.php, database/migrations/2021_03_17_025809_add_field_jenis_registrasi_on_table_rdt_events.php, tests/Feature/RdtEvents/CreateRdtEventTest.php
Refer to task --> https://trello.com/c/NJze8owN
Overview:
- Menambahkan field jenis_registrasi pada kegiatan
- Penyesuaian endpoint API integrasi simlab
Note:
- Tested
=> integrasi pendaftaran jenis rujukan

app/Entities/RdtEvent.php, app/Enums/RegistrationType.php, app/Http/Controllers/Rdt/RdtEventController.php, app/Http/Controllers/SyncToLabkesController.php, app/Http/Requests/Rdt/RdtEventStoreRequest.php, database/factories/RdtEventFactory.php, database/migrations/2021_03_17_025809_add_field_registration_type_on_table_rdt_events.php, tests/Feature/RdtEvents/CreateRdtEventTest.php
Refer to task --> https://trello.com/c/NJze8owN
Overview:
- Mengganti nama field jenis_registrasi menjadi registration_type
- Add kondisi agar kegiatan yang sedang berjalan (tes mandiri) tetap bisa running
Note:
- Tested ketika coba hit API integrasi dengan data existing
cc: mas @yohang88 :grin:
=> Solving issue existing event cant run normally

app/Http/Controllers/SyncToLabkesController.php
Refer to task ---> https://trello.com/c/t9gaiVyh
Overview: 
Mengubah value data category menjadi:
- Jika tes mandiri -> menggunakan data instansi pekerjaan
- Jika tes rujukan -> menggunkana data judul kegiatan
Note:
cc: mas @yohang88 :grin:
=> Change event name to workplace name on category

app/Http/Controllers/SyncToLabkesController.php, app/Http/Resources/RdtEventResource.php
Refer to task --> https://trello.com/c/Zvnx3H1l
Overview:
- Make new variable to contains frequently used property objects
- Add `registration_type` into payload response
Note:
- Tested
=> add registration type to payload response

app/Http/Controllers/Rdt/RdtEventParticipantDetailController.php, app/Http/Controllers/Rdt/RdtInvitationLabResultUpdateController.php, app/Http/Controllers/Rdt/RdtInvitationResetController.php, routes/api.php
Refer to task -> https://trello.com/c/0yt57XiJ/201-tidak-ada-kota-kecamatan-dan-kelurahan-di-detail-peserta-di-dalam-kegiatan
Solved by reading this -> https://laravel.com/docs/8.x/eloquent-relationships#lazy-eager-loading
Overview:
- Fixing bug city, district, village not appear on detail applicant invitation
Note:
- Tested
=> fixing bug city, village, district not appear on detail applicant invitation

.gitignore, app/Http/Controllers/Rdt/RdtCheckEventController.php, app/Http/Controllers/Rdt/RdtEventParticipantDetailController.php, composer.json, phpunit.xml, tests/Feature/RdtCheckEventTest.php
Refer to task --> https://trello.com/c/7wlXTp8b/248-ketika-kegiatan-di-dalam-draft-peserta-tidak-bisa-daftar-di-dalam-kegiatan
Overview:
- Menambahkan value status pada response endpoint `rdt/check-event`
- Menambahkan tdd coverage
Note:
- Tested
=> Add response status event on api rdt event check

.travis.yml, app/Entities/RdtApplicant.php, app/Http/Controllers/Rdt/RdtApplicantController.php, app/Http/Controllers/Rdt/RdtEventParticipantDetailController.php, app/Http/Controllers/Rdt/RdtRegisterController.php, app/Http/Requests/Rdt/RdtApplicantStoreRequest.php, app/Http/Resources/RdtApplicantResource.php, database/factories/RdtApplicantFactory.php, database/migrations/2021_04_01_024520_add_column_registration_at_on_applicants_table.php, resources/views/pdf/applicant.blade.php, tests/Feature/RdtApplicants/ShowRdtApplicantTest.php
Refer to task --> https://trello.com/c/PKQCyuXD/229-registrationat-di-calon-peserta-dan-daftar-peserta
Overview:
- Menambahkan field registration_at pada applicants
- Penyesuaian sorting by registration_at on daftar & calon peserta
- Penyesuaian saat registrasi pada microsite registration_at akan terisi
- Penyesuaian tanggal pendaftaran pada PDF  Bukti Pendaftaran Tes Masif
Note:
=> Add registration at on applicants

app/Entities/RdtEvent.php, app/Http/Controllers/Rdt/RdtEventController.php, app/Http/Resources/RdtEventResource.php, tests/Feature/RdtEvents/ShowRdtEventTest.php
Refer to task --> https://trello.com/c/6B2wz7hE/259-hasil-tes-diganti-menjadi-kirim-hasil-tes
Overview:
- Menambahkan data jumlah peserta yang sudah dikirim hasil tes
- Penyesuaian unit test
Note:
=> add counting notified result on applicants

tests/Feature/RdtEventParticipantListTest.php, tests/Feature/RdtEvents/ListRdtEventTest.php
Overview:
- Add test for uncoverage feature test
=> cicil unit test for uncoverage test

app/Notifications/CheckinThankYou.php, app/Notifications/RdtEventInvitation.php, app/Notifications/RegisterThankYou.php, database/seeds/RdtEventSeeder.php, resources/views/pdf/applicant.blade.php
Refer to task --> https://trello.com/c/8xUqjsZO/268-menghilangkan-kata-tes-masif-di-pendaftaran
Overview:
- Penyesuaian penggunaan kata tes masif 
=> adjustment words "tes masif"

app/Notifications/CheckinThankYou.php, app/Notifications/RdtEventInvitation.php, app/Notifications/TestResult.php
Overview:
- Merubah url https://s.id/tesmasif ke https://s.id/TesCOVID19
cc : mas @yohang88 :grinning:
=> change naming url

app/Http/Requests/Rdt/RdtRegisterRequest.php, tests/Feature/RdtRegisterTest.php
Refer to task --> https://trello.com/c/4He7qLXI/262-revisi-form-pekerjaan-di-link-pendaftaran
Overview:
- Remore validation occupation_type from register microsite
- Adjusment test
cc: mas @yohang88 :grin:
=> remove validation occupation type from microsite

app/Exports/ParticipantListExport.php, app/Http/Controllers/Rdt/RdtEventParticipantListExportF2Controller.php, composer.json, composer.lock, config/app.php, config/excel.php, routes/api.php
Refer on task --> https://trello.com/c/XB4yayaZ/263-import-f2-di-kegiatan
Overview:
- Menambahkan fitur ekspor F2
- Menggunakan laravel-excel package untuk styling column
cc: mas @yohang88 :grin:
=> Add fitur import f2 using laravel excel

app/Exports/ParticipantListExport.php
Overview:
- Tambahan kebutuhan terkait value kode spesimen (diisi kode sample applicant)
Note:
=> update tambahan fitur F2 add code sample on kode spesimen

app/Exports/ParticipantListExport.php
Update requirement fitur Ekspor F2
Overview:
- Tambahan headers title berdasarkan lokasi dan tempat kegiatan
- Tested
=> Update fitur f2 add heading section

Dockerfile
Issue https://github.com/codecasts/php-alpine/issues/131
Overview:
- Re-setup dockerfile for staging
=> re-setup dockerfile

composer.json, composer.lock, config/sentry.php
Update version + sdk sentry to latest (v2.5)
=> update version + sdk sentry to latest (v2.5)

composer.json, composer.lock, config/sentry.php
Up Sentry to Production
- Update version (v2.5) + sdk
- Update config sentry
=> Pr up sentry to prod

Dockerfile, app/Exports/ParticipantListExport.php, composer.json, composer.lock, config/sentry.php
Overview:
- Dockerfile
- UPdate fitur F2
cc:  mas @yohang88
=> PR up to prod Dockerfile

app/Http/Controllers/Rdt/RdtEventNotifyTestResultController.php
Refer to task --> https://trello.com/c/Fyfou9pX/284-sms-hasil-terkirim-meski-hasilnya-belum-ada
Overview:
- Add logic validation to validate only participants who have lab result code to receive blast sms notification
=> fixing issue blast sms through participants lab result is null

app/Http/Controllers/Rdt/RdtEventNotifyTestResultController.php, app/Http/Requests/EventNotifyTestResultRequest.php, resources/lang/en/response.php, resources/lang/id/response.php
Refer to dicussion task --> https://trello.com/c/Fyfou9pX/284-bug-anomaly-kirim-hasil-test
Overview:
- Add exception to throw error when data invitations applicants is null
Note:
=> fixing bug when no picked applicants and add exception to throw error

Dockerfile
Refer task --> https://trello.com/c/dFCKb5Hv/285-update-docker-base-images-to-official
Overview:
- Update docker images to official (base)
=> change images to official

app/Http/Controllers/Rdt/RdtEventParticipantListController.php
Refer to task --> https://trello.com/c/FHLyZEp0/283-detail-kegiatan-filter-tanggal-peserta-checkin-di-detail-kegiatan
Overview:
- Add filter date applicants on detail event 
Note:
=> add filter date on applicants detail event

app/Http/Controllers/Rdt/RdtEventController.php
Refer to task --> https://trello.com/c/u9xpaSTh/282-list-kegiatan-filter-kegiatan-berdasarkan-tanggal-pelaksanaannya
Overview:
- Add filter date by picking up start date and end date
Note:
=> add filter date between start date and end date selected

app/Http/Controllers/Rdt/RdtEventParticipantListController.php
Minor fixing bug :rocket: 
Overview:
- change `where` to `whereDate` to selecting and comparing date filter
=> Fixing bug better to use where date than where when comparing date

app/Http/Controllers/Rdt/RdtEventNotifyTestResultController.php
Refer to task --> https://trello.com/c/Fyfou9pX/284-bug-anomaly-kirim-hasil-test
Overview:
- Remove unused throw on test result notify
=> remove unused throw

app/Http/Controllers/Rdt/RdtApplicantController.php, app/Http/Controllers/Rdt/RdtEventController.php, app/Policies/RdtEventPolicy.php, app/Traits/PaginationTrait.php
Cicil clean code (code smell ) sedikit2 jadi bukit :smile: 
Overview:
- Fixing similar blocks of code (duplicate function)
- Fixing lines of block function (exceeds 25 lines)
- Fixing Cognitive Complexity
- Remove if with [when](https://laravel.com/docs/7.x/helpers#method-fluent-str-when) :smile: 
Note:
- Re tested on Postman 
=> Clean code code smell

app/Http/Controllers/Rdt/RdtApplicantController.php, app/Http/Controllers/Rdt/RdtEventController.php
Refer to task --> https://trello.com/c/u9xpaSTh/282-list-kegiatan-filter-kegiatan-berdasarkan-tanggal-pelaksanaannya
Overview:
- Mengubah default value sorting
- Clean code filter status + date
Note:
=> Minor fixing filter sorting

.github/workflows/continuous-deployment.yml, Dockerfile, app/Http/Controllers/Rdt/RdtEventController.php
Overview:
- Minor fixing bug filter date range between
- Use composer from private registry
Note:
- Smoke tested by QA
=> Up to Production minor hotfix filter date

app/Http/Controllers/Rdt/RdtEventParticipantImportResultController.php, app/Http/Requests/Rdt/RdtInvitationImportRequest.php, app/Rules/LabResultRule.php, resources/lang/en/validation.php, resources/lang/id/response.php, resources/lang/id/validation.php
Refer to task --> https://trello.com/c/J0rsD5LQ/289-validasi-import-hasil-tes
Overview:
- Fixing structure response data error
- Feedback wording
- Add validation for file ( max size, must file )
- Remove validation for `notify` column excel
Note:
=> Fixing structure data

.github/workflows/continuous-deployment.yml, app/Http/Requests/Checkin/RdtCheckinBulkRequest.php, composer.json, composer.lock
Add github action sentry release workflow for adding version info on deployment.
https://docs.sentry.io/product/releases/
https://github.com/marketplace/actions/sentry-release
=> Add github action sentry release workflow

app/Http/Controllers/Rdt/RdtEventParticipantImportResultController.php
Refer to task --> https://trello.com/c/EexHxdHs/291-penambahan-validasi-import-hasil-tes
Overview:
- Add some validation to check file format according to the template used
Note:
- Tested with QA
=> add minor validation to check format according template

app/Http/Controllers/Rdt/RdtEventParticipantImportResultController.php
Refer to task --> https://trello.com/c/EexHxdHs/291-penambahan-validasi-import-hasil-tes
Overview:
- Request feedback to add capitalize on the first word
=> Rewording error response
