- app/Http/Controllers/Rdt/RdtEventController.php
Sebelumnya jika dipilih filter semua pada halaman kegiatan maka sistem akan memunculkan list event yang status nya draft, karna by default ketika halaman kegiatan di akses tidak mengirimkan parameter status. 
PR ini menghadle masalah ini, jadi filter status hanya akan di eksekusi kalau parameter status berisi value draft atau publised, selain itu akan mereturn semua event.
CC : @yohang88 
https://trello.com/c/v7WBtdde/101-kegiatan-bug-filter-status
> handling filter except published and draft

- app/Entities/RdtApplicant.php
perbaikan masalah error Class 'App\Entities\occupationType' not found yang disebabkan kesalahan penulisan nama class.
https://sentry.digitalservice.id/organizations/jabardigitalservice/issues/1412/?project=11&query=is%3Aunresolved
cc : @yohang88
> fix typo class OccupationType name

- app/Http/Controllers/Rdt/RdtEventParticipantListExportF1Controller.php
- config/cors.php
Dugaan root cause penyebab error/gagal saat export format F1:
1. Sebelum ini sebenarnya sudah menggunakan middleware `Fruitcake\Cors\HandleCors` untuk handling CORS (`config/cors.php`), sehingga tidak perlu ditambahkan manual. Jadi beberapa baris `header()` yang ditambahkan manual di controller, bisa dihapus.
2. Problemnya adalah saat Export dengan menggunakan method `openToBrowser`, ternyata library `box/spout` melakukan override response headers terlebih dulu, sehingga headers yang diset oleh middleware `Fruitcake\Cors\HandleCors` jadi tidak terpakai. Sehingga muncul issue CORS.
3. Jadi perbaikannya dengan mengubah export dengan method `openToFile`, namun tidak write ke sebuah file tapi ke PHP stream `php://stdout`. Lalu di controller tersebut mengembalikan `response` berupa `stream`, …
> Fix cors saat export list peserta dengan format F1

- app/Http/Controllers/Rdt/RdtEventParticipantListExportF1Controller.php
penyesuaian value status kesehatan dengan labkes, di labkes tidak ada value status kesehatan not_all dan unknow.
untuk selain jenis status kesehatan yang sudah umum labkes menggunakan value Tanpa Kriteria.
jadi PR ini untuk mengakomodir penyesuaian tersebut.
Related Task :
https://trello.com/c/4Zd6mn2w/141-perubahan-pertanyaan-di-microste
cc : @yohang88
> rewording not_all dan unknown menjadi tanpa keriteria

- app/Http/Controllers/Rdt/RdtEventNotifyTestResultController.php
Perbaikan bug ketika mengirimkan notifikasi tapi waktu notifikasi tidak tecatat di database.
https://trello.com/c/heyfSUDb/130-bug-history-ketika-kirim-hasil
cc : @yohang88
> fix bug waktu pengiriman notifikasi hasil test yang tidak muncul di backoffice

- app/Http/Controllers/Rdt/RdtEventParticipantListController.php
peserta yang sudah di delete dari data master peserta akan muncul sebagai null di list peserta event, PR ini menambahkan filter untuk tidak menampilkan data peserta event yang sudah di hapus.
https://trello.com/c/2x0eS9zj/151-hapus-peserta-ketika-peserta-dihapus-maka-peserta-tersebut-akan-otomatis-terhapus-dari-kegiatan-yang-terdaftar
> menambahkan filter peserta yang sudah dihapus pada list peserta event

- app/Http/Controllers/Rdt/RdtInvitationResetController.php
- routes/api.php
endpoint untuk melakukan reset data kode sampel, lokasi hadir dan waktu hadir dari tabel invitation.
use casenya untuk melakukan reset data yang dilakukan oleh user untuk melakukan testing apakah aplikasi bejalan dengan baik atau tidak, atau jika peserta sudah daftar tapi melarikan diri sehingga data nya perlu di reset.
https://trello.com/c/hbP88FCT/159-detail-kegiatan-admin-bisa-menguncheck-peserta-yang-sudah-check-in-tapi-tidak-mengikuti-tes
cc : @yohang88
> Reset invitation attedance and sample code

- app/Http/Controllers/Rdt/RdtCheckinController.php
- tests/Feature/RdtCheckinTest.php
aplikasi checkin sekarang memungkinkan user untuk melihat daftar event lebih dari satu ketika dia login dan beberapa waktu lalu kejadian ada user yang salah melakukan checkin peserta bukan pada event seharusnya sehingga menyebabkan list peserta yang tercheckin bukan pada event yang mereka ikutin.
PR ini untuk melakukan handling agar peserta yang tidak terdaftar pada event tidak bisa checkin.
https://trello.com/c/Dn3bzFZa/169-peserta-tidak-bisa-check-in-di-kegiatan-yang-tidak-terdaftar
cc : @yohang88
> stop if apllicant not invited

- app/Http/Controllers/Rdt/RdtRegisterController.php
perbaikan salah penulisan nama field pada response key event_end_at, seharusnya pada response event_end_at pakai field end_at bukan start_at.
CC : @yohang88
> perbaikan response event_ent_at setelah register

- app/Http/Controllers/Rdt/RdtRegisterController.php
- app/Listeners/Rdt/InviteToEventByCode.php
sekarang informasi yang muncul setelah daftar adalah tanggal awal dan berakhir event, sedangkan kondisi yang diharapkan sekarang adalah yang muncul tanggal awal dan berakhir kloter dimana peserta tersebut di invite.
PR ini melakukan sedikit perubahan info mulai dan berakhir event menjadi bersumber dari kloter ( jika peserta melakukan pendaftaran menggunakan session id ).
untuk sekarang seluruh pendaftar yang daftar melalui aplikasi langsung masuk ke kloter 1 ( secara default ).
https://trello.com/c/Yy6VooD2/179-peserta-langsung-mendapatkan-kloter-undangan-ketika-mendaftar-dr-link-pendaftaran-supaya-dia-tahu-kapan-dia-bisa-datang-buat-tes
CC : @yohang88
> add event start from schedule

- app/Listeners/Rdt/InviteToEventByCode.php
kondisi sekarang, pikobar_session_id hanya disimpan jika pikobar_session_id = kode_event, selain itu data pikobar_session_id akan jadi null ketika applicant_register.
sekarang ada kebutuhan untuk skenario seperti ini.
admin A membuat event  B dengan durasi 1 hari dan 2 kloter, lalu ketika pendaftaran admin akan memberikan link undangan dengan melakukan modifikasi pikobar_session_id menjadi :
kode_event_B1 untuk calon peserta event B kloter 1 ( http://localhost:52053/#/?sessionId=KODE_EVENT_B1 )
kode_event_B2 untuk calon peserta event B kloter 2 ( http://localhost:52053/#/?sessionId=KODE_EVENT_B2 )
ketika calon peserta melakukan pendaftaran melalui link di atas, peserta tidak langsung di invite ke dalam event.
sehingga admin harus melakukan invite peserta dengan mencari peserta dengan …
> remove condition save pikobar_session_id

- app/Http/Controllers/Rdt/RdtEventParticipantAddController.php
kondisi sekarang, pikobar session id tidak berubah walaupun udah di invite ke event, sehingga ketika admin ingin melakukan invite peserta lagi dengan melakukan pencarian pikobar_session_id maka data peserta tersebut masih muncul. seharusya tidak muncul lagi.
PR ini bertujuan untuk memberikan value null pada pikobar_session_id setelah peserta di invite ke event.
https://trello.com/c/pVRsb87l/190-session-id-terupdate-ketika-peserta-dimasukan-ke-dalam-kegiatan-baru
> set pikobar_session_id to null after invite to event

- app/Http/Controllers/Rdt/RdtEventParticipantAddController.php
- app/Http/Controllers/Rdt/RdtEventParticipantListExportF1Controller.php
update pikobar_seeion_id menjadi event_code ketika di invite dalam event.
perbaikan category menjadi nama event tanggal mulai ( ex : event ABC 23122020 ).
note : yang perbaikan category kemarin saya salah paham, ternyata maksudnya tanggal event bukan tanggal checkin.
https://trello.com/c/mSoG4CTJ/196-daftar-peserta-bug-search-by-session-id
cc : @yohang88
> add event_code to pikobar_session_id

- routes/api.php
Note:
- Terdapat double semicolon on routing develop :smile:  (ini yg menyebabkan case klik button 'Kirim Data' diatas menjadi error 500)
> remove double semicolon on route dev :D

- app/Http/Controllers/Rdt/RdtEventParticipantSetLabCodeController.php
Overview:
- Update endpoint untuk dapat checkin ketika me 'insert' kode sample
- JIka peserta belum checkin maka otomatis akan checkin ketika kode sampel tersedia
- Jika peserta sudah checkin maka waktu dan lokasi checkin tidak berubah
Note:
- Tested
> add-checkin-when-update-kode-sample

- app/Http/Controllers/Rdt/RdtEventParticipantListController.php
- app/Http/Controllers/SyncToLabkesController.php
- app/Http/Resources/RdtInvitationResource.php
- database/migrations/2021_02_16_043716_add_field_status_on_simlab_on_table_rdt_invitations.php
Link task on trello : https://trello.com/c/xMp7UHJd
Overview:
- Menambahkan field migrasi baru bernama 'status_on_simlab' di tabel invitation
- Mengupdate field tersebut pada setiap record yang sukses terkirim maupun yang gagal terkirim ( untuk memudahkan frontend mensortir peserta yang sudah terkirim atau gagal terkirim)
- Response payload sudah menyertakan status setiap peserta
Note:
- Tested
cc mas @yohang88 :smiling_face_with_three_hearts:
> add field status on simlab to received status integrasi peserta

- tests/Feature/RdtRegisterTest.php
Issue : Error deployment because error unit test on update validation rules microsite :grin: 
Overview:
- Symtom_note field can be null (nullable)
Note:
-Tested on pic above :grin: 
> fix unit test field symtoms notes can null

- app/Http/Controllers/Rdt/RdtEventParticipantListController.php
- tests/Feature/RdtEventParticipantListTest.php
Adjustment -> https://trello.com/c/a1LwZY6u/271-bug-preview-peserta-saat-integrasi-simlab
Overview:
- Dapat mendapatkan semua data jika `perPage === null`
- Normal menggunakan pagination jika `perPage` mempunyai `value`
Note:
> make conditional when perpage is null to get all data

- app/Http/Controllers/Rdt/RdtEventController.php
Overview:
- Hotfix minor filter date not working on end date event
Note:
> hotfix filter date not working on end date event

- app/Http/Controllers/Rdt/RdtApplicantController.php
Hotfix production 
Overview:
- Filter pikobar_session_id is not working
Note:
> up hotfix prod filter pikobar session id is not working properly
